spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      datasource:
        master:
          url: jdbc:clickhouse://100.73.89.3:18123/carlos-framework?compress=true&max_execution_time=30
          username: admin
          password: Hadoop@2022
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
