# spring配置
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        # 主库数据�?
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${MYSQL_URL}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: ${MYSQL_USERNAME}
          password: ${MYSQL_PWD}

###############################  缓存数据库配�?#################################
---
spring:
  cache:
    type: redis

