#!/usr/bin/env groovy


// 返回 [tag: xxx, namespace: xxx]
def calcMeta() {
	switch (params.DEPLOY_ENV) {
	case '开发':
            return [tag: 'Alpha', namespace: 'carlos-szt-feature']
        case '测试':
            return [tag: 'Beta', namespace: 'carlos-szt-test']
        case '演示':
            return [tag: 'Release', namespace: 'carlos-szt-demo']
        case '自定义':
            def t = params.IMAGE_TAG?.trim()
            def n = params.NAMESPACE?.trim()
            if (!t || !n) error('custom 模式下 CUSTOM_TAG 和 CUSTOM_NAMESPACE 都必须填写')
            return [tag: t, namespace: n]
        default:   // test/staging/prod 等
            error('参数DEPLOY_ENV不合法！')
    }
}
// 再包一层函数调用，满足 Jenkins 语法
def imageTag()   {
	def date = new Date().format('yyyyMMddHHmm', TimeZone.getTimeZone('Asia/Shanghai'))
    def baseTag = calcMeta().tag          // 你原来的 alpha/dev-123 等
    return "${baseTag}-${date}"
}
def nameSpace()  { return calcMeta().namespace }


/* ========== 常量 ========== */
def repoUrl = scm.userRemoteConfigs[0].url
env.APP_NAME = "${repoUrl.tokenize('/').last().replace('.git', '')}" // 仓库名即服务名

env.PROJECT = params.PROJECT_NAME

pipeline {
	options {
		timeout(time: 30, unit: 'MINUTES')   // 超时时间15分钟
        buildDiscarder(
            logRotator(
                daysToKeepStr: '7',      // 保留 7 天内
                numToKeepStr: '10',      // 最多 20 条
                artifactDaysToKeepStr: '3',  // 工件只留 3 天
                artifactNumToKeepStr: '5'    // 工件最多 5 份
            )
        )
    }
    agent {
		label 'jenkins-agent-pod-template'
    }
    //  agent {
	//	kubernetes {
	//		cloud 'Kubernetes'          // 你的 k8s 云名字，默认就叫 kubernetes
    //           namespace 'devops'   // 运行 agent 的 namespace
    //           inheritFrom 'jenkins-agent-maven-pod'   // ★ 引用刚才保存的模板
    //     }
    //  }
    environment {
		IMAGE_TAG = imageTag()
        NAMESPACE = nameSpace()
        IMAGE_FULL = "${HARBOR_URL}/${PROJECT}/${APP_NAME}:${IMAGE_TAG}"
    }

    stages {
		stage('Maven构建'){
			steps {
				script {
					container('maven') {
						// 把全局 settings.xml 下载到工作区，路径注入变量
                        configFileProvider([configFile(fileId: "b46da426-c66a-400d-a254-68ce05001b12", variable: 'MAVEN_SETTINGS')]){
							// 执行 Maven 命令构建项目，并且设置 Maven 配置为刚刚创建的 Settings.xml 文件
                            sh "mvn -B -U -T 1C clean package deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dmaven.compile.fork=true -Dmaven.compiler.maxmem=2g -Pcarlos-private -s ${MAVEN_SETTINGS}"
                        }
                    }
                }
            }
        }

        /* ======== 1. 构建 & 上传镜像 ======== */
        stage('构建Docker镜像') {
			steps {
				script {
					container('docker') {
						// 提供 Docker 环境，使用 Docker 工具来进行 Docker 镜像构建与推送
                        //def customImage = docker.build("${IMAGE_FULL}", ".")
                        docker.withRegistry("https://${HARBOR_URL}", 'harbor') {
							// 1. 构建
                            //sh """
                            //   export DOCKER_BUILDKIT=1
                            //   docker build \
                            //     --cache-from ${HARBOR_URL}/${PROJECT}/${APP_NAME}:cache \
                            //     -t ${IMAGE_FULL} \
                            //     -t ${HARBOR_URL}/${PROJECT}/${APP_NAME}:cache \
                            //     --build-arg BUILDKIT_INLINE_CACHE=1 .
                            //"""
                            // 2. 推送（仍在 withRegistry 作用域，无需再 login）
                            sh """
                             	docker build -t ${IMAGE_FULL} .
                               docker push ${IMAGE_FULL}
                            """
                            //customImage.push()
                        }
                    }
                }
            }
        }

        stage('Kubernetes 阶段') {
			steps {
				// 去掉嵌套的script块，直接用container
                container('kubectl') {
					script {
						// kubectl 镜像
                        container('kubectl') {
							//直接使用项目内的deployment，这样方便到时候修改
                            def deploy = readFile encoding: "UTF-8", file: "./deploy/deploy.yaml"
                            // 替换部署文件中的变量，并将替换后的文本赋予 deployfile 变量
                            def deployfile = deploy.replaceAll("#APP_NAME","${APP_NAME}")
                                          .replaceAll("#APP_IMAGE_NAME","${IMAGE_FULL}")
                                          .replaceAll("#ENV_LIST","${params.ENV}")
                                          .replaceAll("#NAMESPACE","${NAMESPACE}")
                            // 生成新的 Kubernetes 部署文件，内容为 deployfile 变量中的文本，文件名称为 "deploy.yaml"
                            writeFile encoding: 'UTF-8', file: './deploy.yaml', text: "${deployfile}"
                            // 输出新创建的部署 yaml 文件内容

                            sh "cat deploy.yaml"
                            // 执行 Kuberctl 命令进行部署操作
                            // sh "sleep 9999"
                            sh "kubectl apply -n ${NAMESPACE} -f deploy.yaml"
                            // 可选：等待滚动升级完成
                            sh "kubectl rollout status deployment/${APP_NAME} -n ${NAMESPACE} --timeout=300s"
                        }
                    }
                }
            }
        }
    }

    /* ===== ③ 兜底：任一 stage 失败马上全停 ===== */
    post {
		success {
			echo "✅ 部署成功：${APP_NAME}"
        }
          failure {
			script {
				currentBuild.result = 'ABORTED'
            error("❌ 部署失败，请查看日志")
          }
      }
    }
}
