kind: Deployment
apiVersion: apps/v1
metadata:
  name: carlos-oauth2
  namespace: 412f59bdf18e4417b2305ee70e23c7ff
  labels:
    app: carlos-oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carlos-oauth2
  template:
    metadata:
      labels:
        app: carlos-oauth2
    spec:
      automountServiceAccountToken: false
      containers:
        -
          name: carlos-oauth2
          image:
          ports:
            -
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "1000m"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            -
              name: TZ
              value: Asia/Shanghai
            -
              name: PROFILE
              value: deploy
            -
              name: NACOS_USERNAME
              value: govern
            -
              name: NACOS_PASSWORD
              value: carlos@123456
            -
              name: NACOS_ADDR
              value: 192.168.25.125:18848
            -
              name: NACOS_NAMESPACE
              value: govern-main
            -
              name: NACOS_GROUP
              value: DEFAULT_GROUP







