apiVersion: v1
kind: Pod
spec:
  restartPolicy: Never
  containers:
    # ====== ① JNLP 主容器 ======
    -
      name: jnlp
      image: 'harbor01.yunjin.com/library/jenkins/inbound-agent:alpine'
      args: [ '$(JENKINS_SECRET)', '$(JENKINS_NAME)' ]
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      volumeMounts:
        -
          name: dockersock
          mountPath: /var/run/docker.sock

    # ====== ② Node 构建 ======
    -
      name: "maven"
      env:
        -
          name: "MAVEN_OPTS"
          value: "-Xmx2g -XX:+UseG1GC"
      image: "harbor01.yunjin.com/library/maven:3.8.5-openjdk-17"
      imagePullPolicy: "IfNotPresent"
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 2000m
          memory: 4Gi
      tty: false
      volumeMounts:
        -
          mountPath: "/etc/docker/daemon.json"
          name: "volume-0"
          readOnly: false
        -
          mountPath: "/root/.m2"
          name: "maven-cache"
          readOnly: false
        -
          mountPath: "/home/jenkins/agent/"
          name: "workspace-volume"
          readOnly: false
      workingDir: "/home/jenkins/agent/"

    # ====== ③ Docker CLI（复用宿主机引擎） ======
    -
      name: docker
      image: 'harbor01.yunjin.com/library/docker:19.03.8-dind'
      command: [ 'cat' ]
      tty: true
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 2Gi
      volumeMounts:
        -
          name: dockersock
          mountPath: /var/run/docker.sock
        -
          name: docker-cache
          mountPath: /var/lib/docker
      securityContext:
        privileged: true

    # ====== ④ Kubectl ======
    -
      name: kubectl
      image: 'harbor01.yunjin.com/library/bitnami/kubectl:latest'
      command: [ 'cat' ]
      tty: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  volumes:
    -
      hostPath:
        path: /home/jenkins/agent/.m2
      name: maven-cache
    -
      name: docker-cache
      persistentVolumeClaim:
        claimName: docker-cache-pvc
    -
      name: dockersock
      hostPath:
        path: /var/run/docker.sock

