## 数据库配置
MYSQL_URL: '100.127.6.234:13306/yunjin_msg_feature'
MYSQL_USERNAME: 'root'
MYSQL_PWD: 'yunjin@123456'

#redis配置
REDIS_IP: '100.127.6.234'
REDIS_PORT: '16379'
REDIS_DB: '1'
REDIS_PWD: 'yunjin@123456'
